name: herafy
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.6
  url_launcher: ^6.3.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  awesome_dialog: ^3.2.1
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
